import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import * as XLSX from 'xlsx'
import AdminLayout from '../../components/AdminLayout'
import { getAllTransactionsByDate, getTransactionsByDateRange } from '../../lib/supabase'
import { formatNaira, today, formatDate, formatTime, formatItems, PRODUCTS } from '../../lib/products'

function useAdminGuard() {
  const navigate = useNavigate()
  useEffect(() => { if (sessionStorage.getItem('admin_auth') !== 'true') navigate('/admin') }, [])
  return sessionStorage.getItem('bakery_name') || 'Bakery'
}

// Map product labels to Excel-friendly column headers (# instead of ₦, no commas)
const PRODUCT_HEADERS = PRODUCTS.map(p =>
  p.label.replace('₦', '#').replace(',', '')
)

function downloadXLSX(transactions, label, bakeryName) {
  if (transactions.length === 0) return

  const totalSold = transactions.reduce((s, t) => s + Number(t.total_amount), 0)
  const totalCollected = transactions.reduce((s, t) => s + Number(t.amount_paid), 0)
  const totalDebt = transactions.reduce((s, t) => s + Number(t.debt_for_visit), 0)
  const collectionRate = totalSold > 0 ? totalCollected / totalSold : 0

  // ── Headers ──────────────────────────────────────────────────────────────
  const headers = [
    'S/N',
    'Date',
    'Time',
    'Customer Name',
    'Customer ID',
    'Deliverer',
    ...PRODUCT_HEADERS,
    'Total Goods (N)',
    'Amount Paid (N)',
    'Debt This Visit (N)',
    'Status',
  ]

  // ── Data rows ─────────────────────────────────────────────────────────────
  const dataRows = transactions.map((tx, i) => {
    const items = tx.items || {}
    const productCols = PRODUCTS.map(p => Number(items[p.id] || 0))
    return [
      i + 1,                              // S/N
      formatDate(tx.date),                // Date
      formatTime(tx.created_at),          // Time
      tx.customers?.name || 'Unknown',    // Customer Name
      tx.customers?.customer_code || '',  // Customer ID
      tx.deliverer_name || '',            // Deliverer
      ...productCols,                     // one column per product (numbers)
      Number(tx.total_amount),            // Total Goods (N)
      Number(tx.amount_paid),             // Amount Paid (N)
      Number(tx.debt_for_visit),          // Debt This Visit (N)
      Number(tx.debt_for_visit) > 0 ? 'Debt' : 'Cleared', // Status
    ]
  })

  // ── Summary block ─────────────────────────────────────────────────────────
  const summaryRows = [
    [],                                                         // blank separator
    ['SUMMARY'],
    ['Total Transactions', transactions.length],
    ['Total Goods Sold (N)', totalSold],
    ['Total Amount Collected (N)', totalCollected],
    ['Total Debt (N)', totalDebt],
    ['Collection Rate', collectionRate],                        // decimal → Excel % format
    ['Generated by', bakeryName],
    ['Report Period', label],
    ['Generated on', new Date().toLocaleString('en-NG')],
  ]

  // ── Build worksheet ───────────────────────────────────────────────────────
  const allRows = [headers, ...dataRows, ...summaryRows]
  const ws = XLSX.utils.aoa_to_sheet(allRows)

  // ── Column widths ─────────────────────────────────────────────────────────
  ws['!cols'] = [
    { wch: 5  },  // S/N
    { wch: 18 },  // Date
    { wch: 8  },  // Time
    { wch: 22 },  // Customer Name
    { wch: 12 },  // Customer ID
    { wch: 18 },  // Deliverer
    ...PRODUCTS.map(() => ({ wch: 10 })), // product columns
    { wch: 16 },  // Total Goods (N)
    { wch: 16 },  // Amount Paid (N)
    { wch: 18 },  // Debt This Visit (N)
    { wch: 10 },  // Status
  ]

  // ── Format Collection Rate cell as percentage ─────────────────────────────
  // Collection Rate is in column B of the summary block
  // Row index = 1 (header) + dataRows.length + 1 (blank) + 1 (SUMMARY) + 5 (rows before Collection Rate) + 1-indexed
  const collectionRateRow = 1 + dataRows.length + 1 + 1 + 5 // 1-indexed
  const collectionRateCellRef = XLSX.utils.encode_cell({ r: collectionRateRow, c: 1 })
  if (ws[collectionRateCellRef]) {
    ws[collectionRateCellRef].z = '0.0%'
  }

  // ── Create workbook & export ──────────────────────────────────────────────
  const wb = XLSX.utils.book_new()
  // Sheet name = bakery name (Excel sheet names max 31 chars, no special chars)
  const sheetName = bakeryName.replace(/[:\\/?*\[\]]/g, '').slice(0, 31) || 'Report'
  XLSX.utils.book_append_sheet(wb, ws, sheetName)

  const fileName = `Loafy_Report_${label.replace(/[\s,]/g, '_')}.xlsx`
  XLSX.writeFile(wb, fileName)
}

export default function AdminFinancials() {
  const bakeryName = useAdminGuard()
  const [tab, setTab] = useState('daily')
  const [selectedDate, setSelectedDate] = useState(today())
  const [fromDate, setFromDate] = useState(() => {
    const d = new Date(); d.setDate(d.getDate() - 7); return d.toISOString().split('T')[0]
  })
  const [toDate, setToDate] = useState(today())
  const [transactions, setTransactions] = useState([])
  const [loading, setLoading] = useState(false)

  useEffect(() => { loadData() }, [tab, selectedDate])

  async function loadData() {
    setLoading(true)
    try {
      if (tab === 'daily') {
        const data = await getAllTransactionsByDate(selectedDate)
        setTransactions(data)
      }
    } catch (err) { console.error(err) }
    finally { setLoading(false) }
  }

  async function loadRange() {
    setLoading(true)
    try {
      const data = await getTransactionsByDateRange(fromDate, toDate)
      setTransactions(data)
    } catch { } finally { setLoading(false) }
  }

  const totalSold = transactions.reduce((s, t) => s + Number(t.total_amount), 0)
  const totalCollected = transactions.reduce((s, t) => s + Number(t.amount_paid), 0)
  const totalDebt = transactions.reduce((s, t) => s + Number(t.debt_for_visit), 0)
  const collectionRate = totalSold > 0 ? ((totalCollected / totalSold) * 100).toFixed(1) : '0'

  const byDeliverer = transactions.reduce((acc, tx) => {
    const key = tx.deliverer_name || 'Unknown'
    if (!acc[key]) acc[key] = { sold: 0, collected: 0, debt: 0, count: 0 }
    acc[key].sold += Number(tx.total_amount)
    acc[key].collected += Number(tx.amount_paid)
    acc[key].debt += Number(tx.debt_for_visit)
    acc[key].count++
    return acc
  }, {})

  const reportLabel = tab === 'daily'
    ? formatDate(selectedDate)
    : `${formatDate(fromDate)} to ${formatDate(toDate)}`

  return (
    <AdminLayout title="Financials" bakeryName={bakeryName}>
      <div className="stack stack-lg fade-in">

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '0.75rem' }}>
          <div>
            <h2>Financial Reports</h2>
            <p className="text-muted text-sm" style={{ marginTop: '0.2rem' }}>{reportLabel}</p>
          </div>
          {transactions.length > 0 && (
            <button
              className="btn btn-primary btn-sm"
              onClick={() => downloadXLSX(transactions, reportLabel, bakeryName)}
              style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}
            >
              ⬇️ Download Excel Report
            </button>
          )}
        </div>

        <div className="tabs">
          <button className={`tab-btn${tab === 'daily' ? ' active' : ''}`} onClick={() => setTab('daily')}>Daily</button>
          <button className={`tab-btn${tab === 'range' ? ' active' : ''}`} onClick={() => setTab('range')}>Date Range</button>
        </div>

        {tab === 'daily' && (
          <div className="form-group">
            <label className="form-label">Select Date</label>
            <input type="date" className="form-input" value={selectedDate} onChange={e => setSelectedDate(e.target.value)} max={today()} />
          </div>
        )}

        {tab === 'range' && (
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', alignItems: 'end' }}>
            <div className="form-group"><label className="form-label">From</label><input type="date" className="form-input" value={fromDate} onChange={e => setFromDate(e.target.value)} max={today()} /></div>
            <div className="form-group"><label className="form-label">To</label><input type="date" className="form-input" value={toDate} onChange={e => setToDate(e.target.value)} max={today()} /></div>
            <button className="btn btn-primary" style={{ gridColumn: 'span 2' }} onClick={loadRange}>Generate Report</button>
          </div>
        )}

        {loading ? <div style={{ textAlign: 'center', padding: '2rem' }}><div className="spinner" /></div> : (
          <>
            {transactions.length > 0 && (
              <>
                {/* Summary */}
                <div className="total-bar">
                  <div className="total-bar-row" style={{ marginBottom: '0.5rem' }}>
                    <span className="total-bar-label">Total Sold</span>
                    <span className="total-bar-value">{formatNaira(totalSold)}</span>
                  </div>
                  <hr className="total-bar-divider" />
                  <div className="total-bar-row" style={{ marginBottom: '0.5rem' }}>
                    <span className="total-bar-label">Collected</span>
                    <span style={{ fontWeight: 700, color: 'var(--amber-light)' }}>{formatNaira(totalCollected)}</span>
                  </div>
                  <div className="total-bar-row" style={{ marginBottom: '0.5rem' }}>
                    <span className="total-bar-label">Outstanding Debt</span>
                    <span style={{ fontWeight: 700, color: '#ffaaaa' }}>{formatNaira(totalDebt)}</span>
                  </div>
                  <hr className="total-bar-divider" />
                  <div className="total-bar-row">
                    <span className="total-bar-label">Collection Rate</span>
                    <span style={{ fontWeight: 700, color: Number(collectionRate) >= 80 ? 'var(--amber-light)' : '#ffaaaa' }}>{collectionRate}%</span>
                  </div>
                </div>

                {/* By Deliverer */}
                {Object.keys(byDeliverer).length > 0 && (
                  <div>
                    <div className="section-title" style={{ marginBottom: '0.75rem' }}>Breakdown by Deliverer</div>
                    <div className="data-table-wrap">
                      <table className="data-table">
                        <thead>
                          <tr>
                            <th>Deliverer</th>
                            <th>Visits</th>
                            <th style={{ textAlign: 'right' }}>Sold</th>
                            <th style={{ textAlign: 'right' }}>Collected</th>
                            <th style={{ textAlign: 'right' }}>Debt</th>
                          </tr>
                        </thead>
                        <tbody>
                          {Object.entries(byDeliverer).map(([name, stats]) => (
                            <tr key={name}>
                              <td className="font-semibold">🧑‍🍳 {name}</td>
                              <td>{stats.count}</td>
                              <td style={{ textAlign: 'right' }}>{formatNaira(stats.sold)}</td>
                              <td style={{ textAlign: 'right' }} className="text-success font-semibold">{formatNaira(stats.collected)}</td>
                              <td style={{ textAlign: 'right' }} className={stats.debt > 0 ? 'text-danger font-semibold' : 'text-success'}>{formatNaira(stats.debt)}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}

                {/* Transaction Table */}
                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
                    <div className="section-title">All Transactions ({transactions.length})</div>
                    <button
                      className="btn btn-secondary btn-sm"
                      onClick={() => downloadXLSX(transactions, reportLabel, bakeryName)}
                    >
                      ⬇️ Download Excel
                    </button>
                  </div>
                  <div className="data-table-wrap">
                    <table className="data-table">
                      <thead>
                        <tr>
                          <th>S/N</th>
                          <th>Customer</th>
                          <th>ID</th>
                          <th>Time</th>
                          <th>Deliverer</th>
                          <th>Items</th>
                          <th style={{ textAlign: 'right' }}>Total</th>
                          <th style={{ textAlign: 'right' }}>Paid</th>
                          <th style={{ textAlign: 'right' }}>Debt</th>
                          <th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        {transactions.map((tx, i) => (
                          <tr key={tx.id}>
                            <td style={{ color: 'var(--brown-400)', fontSize: '0.8rem' }}>{i + 1}</td>
                            <td className="font-semibold" style={{ fontSize: '0.875rem' }}>{tx.customers?.name}</td>
                            <td><span style={{ fontFamily: 'monospace', fontSize: '0.75rem', color: 'var(--brown-400)' }}>{tx.customers?.customer_code}</span></td>
                            <td style={{ fontSize: '0.8rem', color: 'var(--brown-400)' }}>{formatTime(tx.created_at)}</td>
                            <td style={{ fontSize: '0.8rem' }}>{tx.deliverer_name}</td>
                            <td style={{ fontSize: '0.78rem', color: 'var(--brown-500)', maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {formatItems(tx.items)}
                            </td>
                            <td style={{ textAlign: 'right' }} className="font-semibold">{formatNaira(tx.total_amount)}</td>
                            <td style={{ textAlign: 'right' }} className="text-success font-semibold">{formatNaira(tx.amount_paid)}</td>
                            <td style={{ textAlign: 'right' }} className={Number(tx.debt_for_visit) > 0 ? 'text-danger font-semibold' : 'text-success'}>
                              {formatNaira(tx.debt_for_visit)}
                            </td>
                            <td>
                              <span className={`badge ${Number(tx.debt_for_visit) > 0 ? 'badge-danger' : 'badge-success'}`}>
                                {Number(tx.debt_for_visit) > 0 ? 'Debt' : 'Cleared'}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </>
            )}

            {transactions.length === 0 && (
              <div className="empty-state" style={{ padding: '3rem' }}>
                <div className="empty-icon">💰</div>
                <div className="empty-title">No transactions found</div>
                <div className="empty-desc">Select a date or date range to view transactions</div>
              </div>
            )}
          </>
        )}
      </div>
    </AdminLayout>
  )
}
